# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4b5d28932776b072e3b4dcb11e8545ccbccf38700b7665d6abd3497b357d06849639125db76c00cf047a9f916962b2e837b83a3b91162310a972fc5c46c3540

test:
  secret_key_base: 31d6d6a995f54bcbf7ddf551ed9fe56c81fcfc7c8242981ccdbff8339c09c2b4cb220d1cb09de789772a4acd76be4d96112edec53dfd4865a8ed1e76ef9eb309

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
